# jekyll-commonmark requires Ruby version >= 2.4.0.
image: ruby:3.0

# add bundle cache to 'vendor' for speeding up builds
cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle config set path 'vendor'
  - bundle install

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch
