name: Murukesh Mohanan
base-url: ""
timezone: Asia/Kolkatta
url: https://muru.dev
enforce_ssl: muru.dev
section_separator: "<!-- section -->"

plugins:
  - jekyll-sitemap
  - jemoji

kramdown:
    input: GFM
    hard_wrap: false

defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"

pages_list:
    About: ''
    CV: 'cv'
    Resources: 'resources'
    Blog: 'blog'

exclude: [vendor, "Gemfile", "Gemfile.lock", "README.md", "LICENSE"]
paginate: 5
paginate_path: "/blog/page:num/"
future: true
