name: Murukesh Mohanan, IIT Bombay
base-url: ""
timezone: Asia/Kolkatta
url: https://murukesh.me
enforce_ssl: murukesh.me
section_separator: "<!-- section -->"

gems:
  - jekyll-sitemap
  - jemoji

kramdown:
    input: GFM
    hard_wrap: false

defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"

pages_list:
    About: ''
    Acads: 'acad'
    Resources: 'resources'
    Blog: 'blog'
    Contact: 'contact'

exclude: [vendor, "Gemfile", "Gemfile.lock"]
paginate: 5
paginate_path: "/blog/page:num/"
