name: Murukesh Mohanan, IIT Bombay
markdown: kramdown
base-url: ""
timezone: Asia/Kolkatta
highlighter: pygments
myurl: http://murukesh.me/
section_separator: "<!-- section -->"

gems:
  - jekyll-sitemap

kramdown:
    input: GFM
    hard_wrap: false

defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"

pages_list:
    Main: ''
    Acads: 'acad'
    Resources: 'resources'
    Blog: 'blog'
    Contact: 'contact'
