name: Murukesh Mohanan, IIT Bombay
markdown: kramdown
root_url: ""
timezone: Asia/Kolkatta
highlighter: pygments

kramdown:
    input: GFM
    hard_wrap: false

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"

pages_list:
    Main: ''
    Acads: 'acad'
    Resources: 'resources'
    Blog: 'blog'
    Contact: 'contact'
